### ISSUE TITLE
Error about port key in the settings dictionary 

### ISSUE THREAD

**Issue by wigging** [ORNL/Zambeze#132]
I installed zambeze from the dev-cleanup branch and tried to run the `imagemagick_files.py` example. I get the key error shown below:

```
Traceback (most recent call last):
  File "~/FlowceptZambeze/zambeze/examples/imagemagick_files.py", line 60, in <module>
    main()
  File "~/FlowceptZambeze/zambeze/examples/imagemagick_files.py", line 56, in main
    campaign.dispatch()
  File "~/FlowceptZambeze/zambeze/zambeze/campaign/campaign.py", line 90, in dispatch
    zmq_port = settings.settings["zmq"]["port"]
KeyError: 'port'
```

It looks like the `ZambezeSettings` class needs a config file. Do I need to provide a config file to run this example? If so, what type of file does this config need to be and what do I put in the file?

**Comment by wigging** [comment]
The config file is located at `~/.zambeze/agent.yaml` after running `zambeze agent start`.
